### PR TITLE
[TASK] Add PSR-2 checking through php-cs-fixer

### PR DESCRIPTION
**Pull request by cedricziel**
Until all projects have been migrated, a special environment
variable `CHECKSTYLE_PSR2` will run the new checks.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Correct me if I'm wrong, but `phpcs` as command would mean we can skip `--dry-run` and get better performance since AFAIK `--dry-run` still causes the rewriting but doesn't write the file.

**Comment by cedricziel** [comment]
Dry run will rewrite in-memory - yep. I don't think we'll experience major performance humps though. Is there any timing information available?

**Comment by NamelessCoder** [comment]
I only have experience to go by, with TYPO3. Running the sniffer alone takes a couple of minutes - running the fixer took nearly an hour (though not dry-running). So for VHS in particular that might be the difference between seconds and minutes.

**Comment by cedricziel** [comment]
Alright. I need little time then to craft a new ruleset.

**Comment by NamelessCoder** [comment]
No rush - swing by the channel if you need my help!

**Comment by cedricziel** [comment]
Alright. - The script will clone the official standard to the vendor directory now, since paths are in uppercase format and relative imports wouldn't work with composer otherwise (what a pity :disappointed:).

**Comment by NamelessCoder** [comment]
Done, but with the raw PSR-2 standard since the TYPO3CMS one clearly isn't designed for community extensions but for the core itself. We can get by just fine with "just" PSR-2.

**Pull request closed without merging**
